sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: vaFnCrW6mVGS9d6ojXkic+VgfRSZ0wOLPMaN81BYZ+mWHeIkuSI0q596lM92JK4ix++3+JTaX6A3tzLJHXCGC8r7nkJUXHXEdLA+8b8dlZXe6P94bwB7GUqrLzrBUJ/FB9HQXqmlLwniuczqzLgvSac6IeGfuK42JsL4ae+TnOW/GUiMjpv8FbME0IVvIb00ezVP6TW+4PJBrLZ3Z9xF9eyH/pxvTZVgTm5dtF1z07rEH0lFKGRcdzrCHi51eUTXxnwXWgpI9i719esAS0fIuytOZFO5XuwT1QXEKYrHi++UGwWPEi+q7I2KE0aTyWfEkkTMLOK9a4TbMeqdHYayfX4/WG9AbN1Y0SnPcmt3h2fccrar2wXEAJGSfNZtKlk9FAuZszU4bR8bmIquDGIKJCbUe7+CVP8khlZv+isoJKGBeiK7t5F15QbHsqQX/s+EqAZAz/YY7JYQG3Kj5qA7lOXsy9rBnuMnsaTl8V9Gqh3ovbHyADO3NYgx7uvjjOSUqR39rry4gT5UAVOLudPv0BJriKZ0Tr6L50WF/W5cQsXWstctxkfSeoBVI26AgLoY7Int/BlM6kfRqXrVYxbvjjKRkfI/+S6sxjoaI8nDsk3z+CZueuy2BYmUOykVCtglQC0VlRozkmgzusWbtBx/YBMFr/Ih7sdm3sC/X6aepg8=
  - secure: Akn45WAq85qQhnat5o3np6EgSYbaX+itEc2HdqlrE7/tHIZWcYk6w2cKd2KyY+BrxAw3J3Yo0y84xvwaGOfy9Wa9hWnNPQV4Itz/fobDlwFbalOu0d0quKbCZdF+7J4sjtCkwYjWtSFAfXS23tTtRf8QRjCdjVBwclKcdQ1+OvmnfBZz66rgOJuv8dLsmMO41N5C0OTv7QOncp3iW8LK5tne2Se1LrI8w9gbuP1NgA16U+zCAwE0Y2e7WH4TepJtaR5WP5kQIET+vXJizKqC2L+quKWPeQja3xdEgVV7gMs1Zbes4RijePDPZXFs5TcNMLz8EJc/UVZvjFob11Xh6pSleD1fYPvq20+jkE/WWIF3ANUA7qPXgrPaBpig7cTcPIsMZUQ41nItaETlug5yqFH/sTvmgDlzNhZ7oPYNucvSR/1hC6Xz1yvt1219vakJWBmA602igbNMvH1Z4QrxSeUqn7BJA/x2PH8zwV8F8WF7st5sYkeqBz1vQM1e6x2sKc2i1I4u9wnf8nZlVWY4EIq/9JoP5I1qi+rU65RCh53XgEJPULADIPIARwP1kbmAbH9vGa1hmRbdIgxAWEaEghJL7QoGnuYd84UT35o/A+3rQ1VMOmyTu5QXZlz2juExGWbbetboTiIY9/kgjhj4vY5bVG3tY7Vrul2+4YJO3H4=
  - secure: CdRxgBrLwGI5zpgFO8JF0ySvoQV6B+hjQRQHiOsadtvDogvXAHBHzFN2+jOzPaINNd/+vk+5WuNovGzV2FwqdCB+3jD0brB73pfjN6bENyUO287wMM83PBlLXDGxf8F5uzJSkP23yIm6O1JTKYHguf3qJ82YOlAfQosyK1dcI80ozNRcBg6o9ksitrUEF1xP6vGk3lM0m5fkOkNr2LwzkbokKO+FnFsTGkqaxKdjGiS6qDpY1p38CkzpBHvSz9/Oq+lYxeARUa3Ko0Z+OO9eI0pLevFoNmdQqTs4hizZ+jusuEaA+I7CvMjbRH3Pvcns37RnN0RiHJYLTpaCLzG6F0SHS/OwlbrUyOmIqknDM3fSryvHgPewaLd3goNpxQyMpksUbpLGwtumq8ShjPaXgf0pw4RWx+jywNKhIpvHP5d0ZLt4nD21cogK/4YJGjNf6078TlmrhhViI4HiyehsoMuzqbZZlrDDUBrTIeZvPC13+KCxeKYSug39w6OwCrMPh4nhAOoL7SuIe4bi8YnUtHdrc1hWN2e6c8ZRs2T9GBfX5/WLTyJrH/RnQyEJAPflb8AeRa9UX/DyFSRCYJpTfz8cn4bhwDT+J7JlrsPfYyGf/dfX41xKQnsbDPmFVP6UZpGsg5eweveqgZ0/h4C+gjNYAv4+L+LJQcmz76pyZO8=
